name: Java App CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java env
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Execute Maven build
      run: mvn --batch-mode --update-snapshots verify

    - name: Upload Jar file
      uses: actions/upload-artifact@master
      with:
        name: app
        path: target/pdftotxt*.jar
