name: Main CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  buid-jar:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Jar file
      run: mvn --batch-mode --update-snapshots verify

    - name: Copy Jar file
      run: mv target/pdftotxt*.jar app.jar

    - name: Upload Jar file
      uses: actions/upload-artifact@master
      with:
        name: app
        path: app.jar

  buid-image:

    runs-on: ubuntu-latest

    steps:
    - name: Build Docker image
      run: docker build . --file Dockerfile ghcr.io/ben69uaq/pdftotxt

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish Docker image
      run: docker push ghcr.io/ben69uaq/pdftotxt:latest
