name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Execute Maven build
      run: mvn --batch-mode --update-snapshots verify
    
    - name: Copy Jar file
      run: mv target/pdftotxt*.jar app.jar

    - name: Upload Jar file
      uses: actions/upload-artifact@master
      with:
        name: jar-file
        path: app.jar
        
  build-image:

    runs-on: ubuntu-latest
    needs: build

    steps:
      
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@master
      with:
        name: jar-file
        path: app.jar

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pdftotxt:$(date +%s)
